CREATE TABLE Customers(
    CustomerID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(100),
    Age NUMBER,
    Balance NUMBER,
    IsVIP VARCHAR2(5) DEFAULT 'FALSE'
);
CREATE TABLE Loans(
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER,
    DueDate DATE,
    FOREIGN KEY(CustomerID) REFERENCES Customerss(CustomerID)
);

INSERT INTO Customers VALUES(1,'Niharika M N',21,47000,'FALSE');
INSERT INTO Customers VALUES(2,'Nandini',28,15000,'FALSE');
INSERT INTO Customers VALUES(3,'Priya',70,12000,'FALSE');
INSERT INTO Customers VALUES(4,'Anita',35,5000,'FALSE');
INSERT INTO Customers VALUES(5,'Vijay',62,20000,'FALSE');

INSERT INTO Loans VALUES(1,1,10,SYSDATE+10);
INSERT INTO Loans VALUES(2,2,8,SYSDATE+45);
INSERT INTO Loans VALUES(3,3,9,SYSDATE+20);
INSERT INTO Loans VALUES(4,4,7,SYSDATE+5);
INSERT INTO Loans VALUES(5,5,11,SYSDATE+25);
